
CREATE TABLE IF NOT EXISTS public.energy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    coal bigint NOT NULL,
    country character varying(255) COLLATE pg_catalog."default",
    date_time timestamp without time zone,
    gas bigint NOT NULL,
    hydro bigint NOT NULL,
    oil bigint NOT NULL,
    other bigint NOT NULL,
    solar bigint NOT NULL,
    wind bigint NOT NULL,
    CONSTRAINT energy_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.energy
    OWNER to admin;



0"Area",0
1"MTU",1
2"Biomass  - Actual Aggregated [MW]",other
3"Fossil Brown coal/Lignite  - Actual Aggregated [MW]",coal
4"Fossil Coal-derived gas  - Actual Aggregated [MW]",gas
5"Fossil Gas  - Actual Aggregated [MW]",gas
6"Fossil Hard coal  - Actual Aggregated [MW]",coal
7"Fossil Oil  - Actual Aggregated [MW]",oil
8"Fossil Oil shale  - Actual Aggregated [MW]",oil
9"Fossil Peat  - Actual Aggregated [MW]",coal
10"Geothermal  - Actual Aggregated [MW]",other
11"Hydro Pumped Storage  - Actual Aggregated [MW]",
12"Hydro Pumped Storage  - Actual Consumption [MW]",
13"Hydro Run-of-river and poundage  - Actual Aggregated [MW]",hydro
14"Hydro Water Reservoir  - Actual Aggregated [MW]",hydro
15"Marine  - Actual Aggregated [MW]",hydro
16"Nuclear  - Actual Aggregated [MW]",nuclear
17"Other  - Actual Aggregated [MW]",other
18"Other renewable  - Actual Aggregated [MW]",other
19"Solar  - Actual Aggregated [MW]",solar
20"Waste  - Actual Aggregated [MW]",other
21"Wind Offshore  - Actual Aggregated [MW]",wind
22"Wind Onshore  - Actual Aggregated [MW]"wind


