
CREATE TABLE IF NOT EXISTS public.energy
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    coal bigint NOT NULL,
    country character varying(255) COLLATE pg_catalog."default",
    date_time timestamp without time zone,
    gas bigint NOT NULL,
    hydro bigint NOT NULL,
    oil bigint NOT NULL,
    other bigint NOT NULL,
    solar bigint NOT NULL,
    wind bigint NOT NULL,
    CONSTRAINT energy_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.energy
    OWNER to admin;



"Area","MTU","Biomass  - Actual Aggregated [MW]","Fossil Brown coal/Lignite  - Actual Aggregated [MW]","Fossil Coal-derived gas  - Actual Aggregated [MW]","Fossil Gas  - Actual Aggregated [MW]","Fossil Hard coal  - Actual Aggregated [MW]","Fossil Oil  - Actual Aggregated [MW]","Fossil Oil shale  - Actual Aggregated [MW]","Fossil Peat  - Actual Aggregated [MW]","Geothermal  - Actual Aggregated [MW]","Hydro Pumped Storage  - Actual Aggregated [MW]","Hydro Pumped Storage  - Actual Consumption [MW]","Hydro Run-of-river and poundage  - Actual Aggregated [MW]","Hydro Water Reservoir  - Actual Aggregated [MW]","Marine  - Actual Aggregated [MW]","Nuclear  - Actual Aggregated [MW]","Other  - Actual Aggregated [MW]","Other renewable  - Actual Aggregated [MW]","Solar  - Actual Aggregated [MW]","Waste  - Actual Aggregated [MW]","Wind Offshore  - Actual Aggregated [MW]","Wind Onshore  - Actual Aggregated [MW]"


